// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	IncrementCounter(ctx context.Context, id uuid.UUID) error
	InsertCounter(ctx context.Context, arg InsertCounterParams) error
	SelectCounter(ctx context.Context, id uuid.UUID) (int32, error)
	UpdateCounter(ctx context.Context, arg UpdateCounterParams) error
}

var _ Querier = (*Queries)(nil)
