FROM alpine
RUN wget https://github.com/myles-mcdonnell/blondie/releases/download/v3.1.2/blondie_linux_amd64
RUN wget https://github.com/go-tooling/modcons/releases/download/1.1.1/modcons_linux_amd64


