version: '3.2'
services:
  publicecho:
    build: .
    environment:
      REMOTE_SERVER_NAME: "privateecho"
      REMOTE_SERVER_PORT: "8080"
    ports:
      - 8082:8080
    depends_on:
      - privateecho
  privateecho:
    build: .
